-- Kecamatan Kebonsari (3519010, 14 desa)
INSERT INTO kelurahans (kecamatan_id, nama, description, geojson) VALUES
(2, 'Bacem', '', NULL),
(2, 'Cabean', '', NULL),
(2, 'Kedondong', '', NULL),
(2, 'Mojorejo', '', NULL),
(2, 'Palur', '', NULL),
(2, 'Pucanganom', '', NULL),
(2, 'Rejosari', '', NULL),
(2, 'Singgahan', '', NULL),
(2, 'Sidorejo', '', NULL),
(2, 'Tambakmas', '', NULL),
(2, 'Tanjungrejo', '', NULL),
(2, 'Kebonsari', '', NULL),
(2, 'Kradinan', '', NULL),

-- Kecamatan Geger (3519020, 19 desa)
(3, 'Banaran', '', NULL),
(3, 'Geger', '', NULL),
(3, 'Jatisari', '', NULL),
(3, 'Jogodayuh', '', NULL),
(3, 'Kaibon', '', NULL),
(3, 'Kertobanyon', '', NULL),
(3, 'Kertosari', '', NULL),
(3, 'Klorogan', '', NULL),
(3, 'Kranggan', '', NULL),
(3, 'Nglandung', '', NULL),
(3, 'Pagotan', '', NULL),
(3, 'Purworejo', '', NULL),
(3, 'Putat', '', NULL),
(3, 'Sambirejo', '', NULL),
(3, 'Sangen', '', NULL),
(3, 'Sareng', '', NULL),
(3, 'Slambur', '', NULL),
(3, 'Sumberejo', '', NULL),
(3, 'Uteran', '', NULL),

-- Kecamatan Dolopo (3519030: 10 desa + 2 kelurahans)
(4, 'Bader', '', NULL),
(4, 'Blimbing', '', NULL),
(4, 'Candimulyo', '', NULL),
(4, 'Doho', '', NULL),
(4, 'Dolopo', '', NULL),
(4, 'Glonggong', '', NULL),
(4, 'Ketawang', '', NULL),
(4, 'Kradinan', '', NULL),
(4, 'Lembah', '', NULL),
(4, 'Suluk', '', NULL),
(4, 'Bangunsari', '', NULL),
(4, 'Mlilir', '', NULL),

-- Kecamatan Dagangan (3519040, 17 desa)
(5, 'Banjarejo', '', NULL),
(5, 'Banjarsari Kulon', '', NULL),
(5, 'Banjarsari Wetan', '', NULL),
(5, 'Dagangan', '', NULL),
(5, 'Jetis', '', NULL),
(5, 'Joho', '', NULL),
(5, 'Kepet', '', NULL),
(5, 'Ketandan', '', NULL),
(5, 'Mendak', '', NULL),
(5, 'Mruwak', '', NULL),
(5, 'Ngranget', '', NULL),
(5, 'Padas', '', NULL),
(5, 'Prambon', '', NULL),
(5, 'Segulung', '', NULL),
(5, 'Sewulan', '', NULL),
(5, 'Sukosari', '', NULL),
(5, 'Tileng', '', NULL),

-- Kecamatan Wungu (3519050, 12 desa + 2 kelurahans)
(6, 'Bantengan', '', NULL),
(6, 'Brumbun', '', NULL),
(6, 'Mojopurno', '', NULL),
(6, 'Mojorayung', '', NULL),
(6, 'Kresek', '', NULL),
(6, 'Ngambel', '', NULL),
(6, 'Nglanduk', '', NULL),
(6, 'Nglambangan', '', NULL),
(6, 'Sobrah', '', NULL),
(6, 'Tempursari', '', NULL),
(6, 'Pulerejo', '', NULL),
(6, 'Ngampet', '', NULL),
(6, 'Munggut', '', NULL),
(6, 'Wungu', '', NULL),

-- Kecamatan Kare (3519060, 8 desa)
(7,'Bodag','',NULL),
(7,'Bolo','',NULL),
(7,'Cermo','',NULL),
(7,'Kare','',NULL),
(7,'Kepel','',NULL),
(7,'Kuwiran','',NULL),
(7,'Morang','',NULL),
(7,'Randualas','',NULL),

-- Kecamatan Gemarang (3519070, 7 desa)
(8,'Batok','',NULL),
(8,'Durenan','',NULL),
(8,'Gemarang','',NULL),
(8,'Nampu','',NULL),
(8,'Sebayi','',NULL),
(8,'Tawangrejo','',NULL),
(8,'Winong','',NULL),

-- Kecamatan Saradan (3519120, 15 desa)
(9,'Bajulan','',NULL),
(9,'Bandungan','',NULL),
(9,'Bongsopotro','',NULL),
(9,'Bener','',NULL),
(9,'Klangon','',NULL),
(9,'Klumutan','',NULL),
(9,'Ngepeh','',NULL),
(9,'Pajaran','',NULL),
(9,'Sambirejo','',NULL),
(9,'Sidorejo','',NULL),
(9,'Sugihwaras','',NULL),
(9,'Sukorejo','',NULL),
(9,'Sumberbendo','',NULL),
(9,'Sumbersari','',NULL),
(9,'Tulung','',NULL),

-- Kecamatan Pilangkenceng (3519130, 18 desa)
(10,'Bulu','',NULL),
(10,'Dawuhan','',NULL),
(10,'Duren','',NULL),
(10,'Gandul','',NULL),
(10,'Kedungbanteng','',NULL),
(10,'Kedungmaron','',NULL),
(10,'Kedungrejo','',NULL),
(10,'Kenongorejo','',NULL),
(10,'Krebet','',NULL),
(10,'Luworo','',NULL),
(10,'Muneng','',NULL),
(10,'Ngale','',NULL),
(10,'Ngengor','',NULL),
(10,'Pilangkenceng','',NULL),
(10,'Pulerejo','',NULL),
(10,'Purworejo','',NULL),
(10,'Sumbergandu','',NULL),
(10,'Wonoayu','',NULL),

-- Kecamatan Mejayan (3519100, 11 desa + 3 kelurahans)
(11,'Blabakan','',NULL),
(11,'Darmorejo','',NULL),
(11,'Kaligunting','',NULL),
(11,'Kaliabu','',NULL),
(11,'Kebonagung','',NULL),
(11,'Klecorejo','',NULL),
(11,'Kuncen','',NULL),
(11,'Mejayan','',NULL),
(11,'Ngampel','',NULL),
(11,'Sidodadi','',NULL),
(11,'Wonorejo','',NULL),
(11,'Bangunsari','',NULL),
(11,'Krajan','',NULL),
(11,'Pandean','',NULL),

-- Kecamatan Wonoasri (3519110, 10 desa)
(12,'Banyukambang','',NULL),
(12,'Bancong','',NULL),
(12,'Buduran','',NULL),
(12,'Jatirejo','',NULL),
(12,'Klitik','',NULL),
(12,'Ngadirejo','',NULL),
(12,'Plumpungrejo','',NULL),
(12,'Purwosari','',NULL),
(12,'Sidomulyo','',NULL),
(12,'Wonoasri','',NULL),

-- Kecamatan Balerejo (3519120? Actually 351910? check) — ID kode 35.19.10 (351910)
(13,'Babadan Lor','',NULL),
(13,'Balerejo','',NULL),
(13,'Banaran','',NULL),
(13,'Bulakrejo','',NULL),
(13,'Gading','',NULL),
(13,'Garon','',NULL),
(13,'Glonggong','',NULL),
(13,'Jerukgulung','',NULL),
(13,'Kebonagung','',NULL),
(13,'Kedungjati','',NULL),
(13,'Kedungrejo','',NULL),
(13,'Kuwu','',NULL),
(13,'Pacinan','',NULL),
(13,'Simo','',NULL),
(13,'Sogo','',NULL),
(13,'Sumberbening','',NULL),
(13,'Tapelan','',NULL),
(13,'Warurejo','',NULL),

-- Kecamatan Madiun (3519080, 12 desa + 1 kelurahans)
(14,'Bagi','',NULL),
(14,'Banjarsari','',NULL),
(14,'Betek','',NULL),
(14,'Dempelan','',NULL),
(14,'Dimong','',NULL),
(14,'Gunungsari','',NULL),
(14,'Sendangrejo','',NULL),
(14,'Sirapan','',NULL),
(14,'Sumberejo','',NULL),
(14,'Tanjungrejo','',NULL),
(14,'Tiron','',NULL),
(14,'Tulungrejo','',NULL),
(14,'Nglames','',NULL),

-- Kecamatan Sawahan (3519140, 13 desa)
(15,'Bakur','',NULL),
(15,'Cabean','',NULL),
(15,'Golan','',NULL),
(15,'Kajang','',NULL),
(15,'Kanung','',NULL),
(15,'Klumpit','',NULL),
(15,'Krokeh','',NULL),
(15,'Lebak Ayu','',NULL),
(15,'Pucangrejo','',NULL),
(15,'Pule','',NULL),
(15,'Rejosari','',NULL),
(15,'Sawahan','',NULL),
(15,'Sidomulyo','',NULL),

-- Kecamatan Jiwan (3519150, 14 desa)
(16,'Bedoho','',NULL),
(16,'Bibrik','',NULL),
(16,'Bukur','',NULL),
(16,'Jiwan','',NULL),
(16,'Grobogan','',NULL),
(16,'Kincang Wetan','',NULL),
(16,'Sukolilo','',NULL),
(16,'Klagenserut','',NULL),
(16,'Kwangsen','',NULL),
(16,'Metesih','',NULL),
(16,'Ngetrep','',NULL),
(16,'Sambirejo','',NULL),
(16,'Teguhan','',NULL),
(16,'Wayut','',NULL);
